name: SwiftDexExample
options:
  bundleIdPrefix: com.hagmas
packages:
  SwiftDex:
    path: ../
targets:
  SwiftDexExample:
    type: application
    platform: macOS
    deploymentTarget: '26.0'
    settings:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 6.0
    dependencies:
      - package: SwiftDex
    sources:
        - SwiftDexExample

