# https://github.com/actions/runner-images

name: test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_26.3.app

jobs:
  test:
    name: Test
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Test library
        run: scripts/test.sh

  validation:
    name: Validation
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Show environments
        run: |
          swift --version
          xcodebuild -version
      - name: Validate lint
        run: make lint
      - name: Validate format
        run: |
          make format
          if [ -n "$(git status --porcelain)" ]; then echo "Make sure that the code is formated by 'make format'."; exit 1; fi
